In [9]:
import pandas as pd

In [10]:
nashzips = pd.read_excel('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/nashzipcodes.xlsx')

In [11]:
ziplist = nashzips['zip'].to_list()

In [12]:
ziplist

[37216,
 37204,
 37221,
 37212,
 37209,
 37206,
 37217,
 37219,
 37218,
 37232,
 37213,
 37205,
 37203,
 37201,
 37214,
 37240,
 37208,
 37207,
 37215,
 37228,
 37210,
 37211,
 37220]

In [13]:
nashdisease2016 = pd.read_csv('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/CDC data/CSVs/nashdisease2016.csv')
nashdisease2017 = pd.read_csv('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/CDC data/CSVs/nashdisease2017.csv')
nashdisease2018 = pd.read_csv('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/CDC data/CSVs/fixednashdisease2018.csv')
nashdisease2019 = pd.read_csv('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/CDC data/CSVs/nashdisease2019.csv')

In [14]:
tractzip16 = pd.read_excel('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/crosswalk files/TRACT_ZIP_032016.xlsx')
tractzip17 = pd.read_excel('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/crosswalk files/TRACT_ZIP_032017.xlsx')
tractzip18 = pd.read_excel('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/crosswalk files/TRACT_ZIP_032018.xlsx')
tractzip19 = pd.read_excel('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/crosswalk files/TRACT_ZIP_032019.xlsx')

In [15]:
tractzip16.head(2)

        TRACT    ZIP  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
0  1001020100  36067   1.000000   1.000000   1.000000   1.000000
1  1001020200  36067   0.412394   0.417355   0.947368   0.420353

In [22]:
testmask = tractzip16['ZIP'].isin(ziplist)

In [23]:
test = tractzip16[testmask]

In [24]:
test

              TRACT    ZIP  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
134651  47021070102  37209   0.011357   0.000000   0.000000   0.011099
134847  47037010105  37218   0.807269   0.437500   0.000000   0.800000
134849  47037010106  37207   0.489756   0.771429   0.000000   0.499057
134850  47037010106  37218   0.080976   0.000000   0.000000   0.078302
134852  47037010201  37207   0.433047   0.408163   0.666667   0.432975
...             ...    ...        ...        ...        ...        ...
137868  47187050403  37221   0.281088   0.000000   0.000000   0.280000
137870  47187050404  37221   0.190572   0.062500   0.000000   0.189676
137872  47187050404  37215   0.016116   0.000000   0.000000   0.016006
137874  47187050405  37221   0.031712   0.000000   0.000000   0.031480
137880  47187050502  37221   0.001959   0.000000   0.000000   0.001849

[220 rows x 6 columns]

In [ ]:
tractzip16_dict = pd.concat([tractzip16])

In [5]:
nashdisease2016.head(2)

,Unnamed: 0,StateAbbr,PlaceName,PlaceFIPS,TractFIPS,Place_TractID,Population2010,ACCESS2_CrudePrev,ACCESS2_Crude95CI,ARTHRITIS_CrudePrev,...,PAPTEST_Crude95CI,PHLTH_CrudePrev,PHLTH_Crude95CI,SLEEP_CrudePrev,SLEEP_Crude95CI,STROKE_CrudePrev,STROKE_Crude95CI,TEETHLOST_CrudePrev,TEETHLOST_Crude95CI,Geolocation
0,22333,TN,Nashville,4752006,47037014400,4752006-47037014400,1250,26.7,"(22.4, 30.8)",27.5,...,"(76.9, 82.4)",18.6,"(16.7, 20.6)",45.2,"(43.3, 47.0)",4.6,"( 4.1, 5.1)",31.9,"(22.3, 41.2)","36.1576629645, -86.8057331508"
1,22334,TN,Nashville,4752006,47037010801,4752006-47037010801,5363,19.7,"(17.3, 22.1)",28.0,...,"(81.5, 85.1)",15.3,"(14.1, 16.6)",38.7,"(37.3, 39.9)",3.4,"( 3.1, 3.7)",21.4,"(15.4, 28.3)","36.2758406196, -86.7227516725"

In [7]:
disease16tracts = nashdisease2016['TractFIPS'].unique().tolist()

In [8]:
disease16tracts

[47037014400,
 47037010801,
 47037019115,
 47037010104,
 47037015802,
 47037011800,
 47037018804,
 47037012701,
 47037018301,
 47037015300,
 47037015614,
 47037016000,
 47037017100,
 47037017000,
 47037011300,
 47037013100,
 47037018000,
 47037015619,
 47037017402,
 47037010401,
 47037015613,
 47037019108,
 47037018803,
 47037015627,
 47037016500,
 47037018500,
 47037011001,
 47037019200,
 47037012702,
 47037015501,
 47037018905,
 47037013602,
 47037010105,
 47037013700,
 47037011900,
 47037018405,
 47037019114,
 47037012100,
 47037018203,
 47037018904,
 47037010802,
 47037015623,
 47037017702,
 47037014300,
 47037015628,
 47037010202,
 47037019109,
 47037018101,
 47037010601,
 47037019005,
 47037015618,
 47037017401,
 47037015700,
 47037015200,
 47037011200,
 47037013000,
 47037019006,
 47037017800,
 47037018601,
 47037010502,
 47037015900,
 47037013400,
 47037013800,
 47037013300,
 47037019118,
 47037010904,
 47037018404,
 47037015629,
 47037015502,
 47037015624,
 47037016600,
 47037015609,
 47037016200,
 47037017701,
 47037012200,
 47037018401,
 47037015402,
 47037019117,
 47037016700,
 47037015622,
 47037017300,
 47037015804,
 47037011600,
 47037018902,
 47037019110,
 47037010602,
 47037018408,
 47037010901,
 47037015100,
 47037018602,
 47037010201,
 47037019400,
 47037015617,
 47037018102,
 47037011100,
 47037013500,
 47037019004,
 47037013900,
 47037019105,
 47037019500,
 47037015630,
 47037015625,
 47037018409,
 47037011500,
 47037012802,
 47037017901,
 47037015404,
 47037015610,
 47037010501,
 47037018201,
 47037016300,
 47037016800,
 47037013202,
 47037015615,
 47037016100,
 47037015401,
 47037019111,
 47037010701,
 47037010103,
 47037018302,
 47037018901,
 47037010903,
 47037015620,
 47037017200,
 47037011700,
 47037015803,
 47037014800,
 47037012600,
 47037019116,
 47037018407,
 47037018700,
 47037015612,
 47037015631,
 47037015405,
 47037017500,
 47037016900,
 47037018410,
 47037011002,
 47037019300,
 47037019600,
 47037013201,
 47037014200,
 47037017902,
 47037010402,
 47037013601,
 47037015626,
 47037018202,
 47037016400,
 47037010106,
 47037011400,
 47037019106,
 47037012801,
 47037018801,
 47037019003,
 47037019112,
 47037010702]