In [20]:
import pandas as pd

In [2]:
# list of municipal nashville zipcodes that i am using for my project

nashzips = pd.read_excel('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/nashzipcodes.xlsx')
ziplist = nashzips['zip'].to_list()
ziplist

[37216,
 37204,
 37221,
 37212,
 37209,
 37206,
 37217,
 37219,
 37218,
 37232,
 37213,
 37205,
 37203,
 37201,
 37214,
 37240,
 37208,
 37207,
 37215,
 37228,
 37210,
 37211,
 37220]

In [3]:
# importing my nashville disease data

nashdisease2016 = pd.read_csv('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/CDC data/CSVs/nashdisease2016.csv')
nashdisease2017 = pd.read_csv('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/CDC data/CSVs/nashdisease2017.csv')
nashdisease2018 = pd.read_csv('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/CDC data/CSVs/fixednashdisease2018.csv')
nashdisease2019 = pd.read_csv('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/CDC data/CSVs/nashdisease2019.csv')

In [4]:
# importing the HUD crosswalk tract to zip data

tractzip16 = pd.read_excel('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/crosswalk files/TRACT_ZIP_032016.xlsx')
tractzip17 = pd.read_excel('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/crosswalk files/TRACT_ZIP_032017.xlsx')
tractzip18 = pd.read_excel('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/crosswalk files/TRACT_ZIP_032018.xlsx')
tractzip19 = pd.read_excel('/Users/k.simmons/Desktop/NSS/data analytics bootcamp/capstone/Data/crosswalk files/TRACT_ZIP_032019.xlsx')

In [106]:
nashdisease2016.head(2)

,Unnamed: 0,StateAbbr,PlaceName,PlaceFIPS,TractFIPS,Place_TractID,Population2010,ACCESS2_CrudePrev,ACCESS2_Crude95CI,ARTHRITIS_CrudePrev,...,PAPTEST_Crude95CI,PHLTH_CrudePrev,PHLTH_Crude95CI,SLEEP_CrudePrev,SLEEP_Crude95CI,STROKE_CrudePrev,STROKE_Crude95CI,TEETHLOST_CrudePrev,TEETHLOST_Crude95CI,Geolocation
0,22333,TN,Nashville,4752006,47037014400,4752006-47037014400,1250,26.7,"(22.4, 30.8)",27.5,...,"(76.9, 82.4)",18.6,"(16.7, 20.6)",45.2,"(43.3, 47.0)",4.6,"( 4.1, 5.1)",31.9,"(22.3, 41.2)","36.1576629645, -86.8057331508"
1,22334,TN,Nashville,4752006,47037010801,4752006-47037010801,5363,19.7,"(17.3, 22.1)",28.0,...,"(81.5, 85.1)",15.3,"(14.1, 16.6)",38.7,"(37.3, 39.9)",3.4,"( 3.1, 3.7)",21.4,"(15.4, 28.3)","36.2758406196, -86.7227516725"

In [107]:
# creating filter for census tracts that are only found in the disease data

tractmask = nashdisease2016['TractFIPS'].to_list()

In [108]:
# filtering tractzip16 to only show the tracts that are found in the disease data

diseasetracts16 = tractzip16['TRACT'].isin(tractmask)
nashtractzip16 = tractzip16[diseasetracts16]
nashtractzip16.head(2)

              TRACT    ZIP  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
134840  47037010103  37072   0.254545        0.0        0.0   0.252133
134841  47037010103  37080   0.715789        1.0        0.0   0.718483

In [109]:
# now that tractzip16 contains only revelant tracts, filtering further to only include zips from ziplist

zipfilter16 = nashtractzip16['ZIP'].isin(ziplist)
nashtractzip16 = nashtractzip16[zipfilter16]
nashtractzip16.head(2)

              TRACT    ZIP  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
134847  47037010105  37218   0.807269   0.437500        0.0   0.800000
134849  47037010106  37207   0.489756   0.771429        0.0   0.499057

In [110]:
#dropping unnecessary columns

nashtractzip16 = nashtractzip16.drop(['RES_RATIO', 'BUS_RATIO', 'OTH_RATIO', 'TOT_RATIO'], axis=1)
nashtractzip16.head(2)

              TRACT    ZIP
134847  47037010105  37218
134849  47037010106  37207

In [111]:
#resetting index, and then setting tract number to index for ease of making dictionary using .to_dict()

nashtractzip16 = nashtractzip16.reset_index(drop=True)
nashtractzip16.set_index('TRACT', inplace=True)
nashtractzip16.head(2)

               ZIP
TRACT
47037010105  37218
47037010106  37207

In [112]:
tractzip16_dict = nashtractzip16.to_dict()

In [113]:
tractzip16_dict

{'ZIP': {47037010105: 37218,
  47037010106: 37218,
  47037010201: 37207,
  47037010702: 37216,
  47037010802: 37216,
  47037010901: 37207,
  47037010903: 37207,
  47037010904: 37207,
  47037011001: 37207,
  47037011002: 37216,
  47037011100: 37216,
  47037011200: 37216,
  47037011300: 37207,
  47037011400: 37216,
  47037011500: 37206,
  47037011600: 37216,
  47037011700: 37207,
  47037011800: 37207,
  47037011900: 37207,
  47037012100: 37206,
  47037012200: 37206,
  47037012600: 37207,
  47037012701: 37207,
  47037012702: 37218,
  47037012801: 37218,
  47037012802: 37218,
  47037013000: 37209,
  47037013100: 37218,
  47037013201: 37209,
  47037013202: 37209,
  47037013300: 37209,
  47037013400: 37209,
  47037013500: 37209,
  47037013601: 37208,
  47037013602: 37208,
  47037013700: 37228,
  47037013800: 37208,
  47037013900: 37208,
  47037014200: 37208,
  47037014300: 37209,
  47037014400: 37203,
  47037014800: 37210,
  47037015100: 37214,
  47037015200: 37210,
  47037015300: 37214,
  47037015501: 37214,
  47037015502: 37214,
  47037015612: 37217,
  47037015613: 37211,
  47037015614: 37217,
  47037015615: 37217,
  47037015617: 37217,
  47037015618: 37217,
  47037015620: 37217,
  47037015624: 37214,
  47037015625: 37217,
  47037015626: 37217,
  47037015700: 37217,
  47037015802: 37217,
  47037015803: 37217,
  47037015804: 37217,
  47037015900: 37210,
  47037016000: 37210,
  47037016100: 37204,
  47037016200: 37203,
  47037016300: 37212,
  47037016400: 37212,
  47037016500: 37240,
  47037016600: 37203,
  47037016700: 37215,
  47037016800: 37212,
  47037016900: 37212,
  47037017000: 37203,
  47037017100: 37204,
  47037017200: 37210,
  47037017300: 37210,
  47037017401: 37211,
  47037017402: 37211,
  47037017500: 37204,
  47037017701: 37204,
  47037017702: 37204,
  47037017800: 37212,
  47037017901: 37205,
  47037017902: 37204,
  47037018000: 37215,
  47037018101: 37209,
  47037018102: 37209,
  47037018201: 37205,
  47037018202: 37221,
  47037018203: 37205,
  47037018301: 37221,
  47037018302: 37221,
  47037018401: 37209,
  47037018404: 37205,
  47037018405: 37221,
  47037018407: 37221,
  47037018408: 37221,
  47037018409: 37221,
  47037018410: 37221,
  47037018500: 37215,
  47037018601: 37215,
  47037018602: 37220,
  47037018700: 37220,
  47037018801: 37211,
  47037018804: 37211,
  47037018901: 37211,
  47037018902: 37220,
  47037018904: 37211,
  47037018905: 37211,
  47037019003: 37211,
  47037019004: 37211,
  47037019005: 37211,
  47037019006: 37211,
  47037019105: 37211,
  47037019106: 37211,
  47037019108: 37211,
  47037019109: 37211,
  47037019110: 37211,
  47037019111: 37211,
  47037019112: 37211,
  47037019114: 37211,
  47037019115: 37211,
  47037019116: 37211,
  47037019200: 37213,
  47037019300: 37213,
  47037019400: 37219,
  47037019500: 37219,
  47037019600: 37210}}

In [114]:
tractzip16_dict['ZIP'][47037015405]

KeyError: 47037015405